### ISSUE TITLE
[package.json] Is there a faster way to call the tool from the command line?

### ISSUE THREAD

**Issue by kaby76** [mike-lischke/antlr-ng#15]
This script in package.json (https://github.com/mike-lischke/antlr-ng/blob/e9423bbd9c83a8f2581be1e84282075c32a59483/package.json#L56) calls the Antlr Tool. It works fine, but the call to generate the parser is slow. For example, for [abb](https://github.com/antlr/grammars-v4/tree/7f917add1199e8b050a7117814899ebab50a3c3b/abb), taking 16s. (It becomes a problem with two top-level .g4's because I generate separate calls to the tool in order to make sure the .tokens are generated according to the proper topologic sort of teh .g4 dependencies. For `350 .g4's * ~2 * 16s per .g4`, the overhead is 18m just to call the tool for every grammar in grammars-g4.)  I suspect that's because it calls the tsc compiler on the antlr-ng to generate .js code that node can then execute. Is there command-line call that is faster?

**Comment by mike-lischke** [comment]
That is something I want to improve by adding support for a glob pattern for grammar files. But that requires better handling for the output.

Btw. there's probably a quick solution for you. That script you mentioned is outdated. That should actually be:

> "run": "tsx cli/runner.ts --version",

tsx does not do any type checking, so it is much faster.

**Comment by mike-lischke** [comment]
I added another patch which introduces glob patterns for grammar file names (something like `grammar-v4/**/*g4`), but the handling is not perfect yet, because generation stops as soon as one grammar caused an error. That must be changed in a way that considers the grammar path and only stops processing grammars in that particular folder, where the handling failed.

**Comment by mike-lischke** [comment]
Oh, and the original way of specifying grammars still works, of course.

**Comment by kaby76** [comment]
> "run": "tsx cli/runner.ts --version",
```
build.sh: line 18: tsx: command not found
```
Somewhere along the way, we need to straighten out all the dependencies required in a "vanilla" Ubuntu environment (actually, "ubuntu-latest", which was just updated in the last few weeks, and really contains way too much junk). `npm i tsx` doesn't work. And, it's not on this list either:
```
ken@DESKTOP-DL44R7B:~/antlr-ng$ tsx

Command 'tsx' not found, did you mean:

  command 'tex' from deb texlive-binaries (2019.20190605.51237-3ubuntu0.1)
  command 'ttx' from deb fonttools (4.5.0-1)
  command 'tst' from deb pvm-examples (3.4.6-2build2)
  command 'osx' from deb opensp (1.5.2-13ubuntu3)
  command 'tx' from deb transifex-client (0.13.5-2)
  command 'tsc' from deb node-typescript (3.8.3-1)
  command 'tox' from deb tox (3.13.2-2)
  command 'sx' from deb lrzsz (0.12.21-10)
  command 'tsxs' from deb trafficserver-dev (8.0.5+ds-3)
  command 'ts' from deb moreutils (0.63-1)
  command 'tsp' from deb task-spooler (1.0-1)

Try: sudo apt install <deb name>

ken@DESKTOP-DL44R7B:~/antlr-ng$
```

**Comment by mike-lischke** [comment]
You are in a special situation @kaby76, which is usually not the case when people use the tool later. When you pull the repo please always inspect package.json, if that file changed. If it did you have to clean and re-install your node packages (remove node_modules and package.lock.json and run `npm i` again).
