### ISSUE TITLE
"// Generated from b.g4 by ANTLR 0.4.0" -- can we change this for Antlr-ng?

### ISSUE THREAD

**Issue by kaby76** [mike-lischke/antlr-ng#21]
Right now, the generated parser and lexer files contain `// Generated from .....g4 by ANTLR 0.4.0`. Is it possible to change the string "ANTLR" to something that is specific for Antlr-ng? Or, is the plan to make that "ANTLR 5......"? 👍

**Comment by mike-lischke** [comment]
This is part of the target templates, e.g. the C++ File.stg contains this:

> fileHeader(grammarFileName, ANTLRVersion, header) ::= <<
<header>

// Generated from <grammarFileName> by ANTLR <ANTLRVersion>
>>

**Comment by mike-lischke** [comment]
Side node: TP didn't allow me to use ANLTR5 for my fork, but instead gave permission just a few weeks later (after I asked him) to another project, which is now dead, so my project is named antlr-ng until I can come up with a better name.
