### ISSUE TITLE
Antlr tool works for "abb" grammar, but fails with "cpp" grammar with "implicit definition" warnings.

### ISSUE THREAD

**Issue by kaby76** [mike-lischke/antlr-ng#22]
This one is a little baffling. Attached are the .g4's for the [abb grammar](https://github.com/antlr/grammars-v4/tree/7f917add1199e8b050a7117814899ebab50a3c3b/abb) and the [cpp grammar](https://github.com/antlr/grammars-v4/tree/7f917add1199e8b050a7117814899ebab50a3c3b/cpp). Both are split grammars. [abb-cpp.zip](https://github.com/user-attachments/files/18264155/abb-cpp.zip)

The first grammar "abb" builds and tests just fine. I've included the .g4's and a trimmed down build.sh that only invokes the tool.

The second grammar is "cpp". The build.sh first generates the lexer recognizer and the .tokens file. It then calls the Antlr Tool for the CPP14Parser.g4 file. However, this time, the tool outputs some unusual errors:
```
ken@DESKTOP-DL44R7B:~/grammars-v4/cpp/Generated-Antlr4ng$ bash build.sh
warning(125): CPP14Parser.g4:79:6: implicit definition of token LeftBracket in parser
warning(125): CPP14Parser.g4:79:33: implicit definition of token RightBracket in parser
warning(125): CPP14Parser.g4:6:11: implicit definition of token Dynamic_cast in parser
warning(125): CPP14Parser.g4:6:42: implicit definition of token Static_cast in parser
warning(125): CPP14Parser.g4:6:72: implicit definition of token Reinterpret_cast in parser
warning(125): CPP14Parser.g4:6:107: implicit definition of token Const_cast in parser
warning(125): CPP14Parser.g4:12:60: implicit definition of token Dot in parser
warning(125): CPP14Parser.g4:163:6: implicit definition of token Not in parser
warning(125): CPP14Parser.g4:198:6: implicit definition of token Noexcept in parser
warning(125): CPP14Parser.g4:240:21: implicit definition of token Caret in parser
warning(125): CPP14Parser.g4:303:69: implicit definition of token Default in parser
warning(125): CPP14Parser.g4:401:6: implicit definition of token Static_assert in parser
warning(125): CPP14Parser.g4:436:6: implicit definition of token Explicit in parser
warning(125): CPP14Parser.g4:465:6: implicit definition of token Short in parser
warning(125): CPP14Parser.g4:483:6: implicit definition of token Int in parser
warning(125): CPP14Parser.g4:485:6: implicit definition of token Float in parser
warning(125): CPP14Parser.g4:532:20: implicit definition of token Struct in parser
warning(125): CPP14Parser.g4:648:23: implicit definition of token Const in parser
```
This works fine with the old antlr tool. In addition, the symbols, like `LeftBracket`, exist in the lexer .tokens file. The tool didn't say it couldn't find the tokenVocab, so I don't know.

**Comment by mike-lischke** [comment]
Probably the tokens are not found for the Cpp grammar. Need to check this out...
