### ISSUE TITLE
antlr-ng generated Java recognizers have 0.4.0 for version. Conflicts with "official" Antlr4 Java runtime. Port works otherwise!!

### ISSUE THREAD

**Issue by kaby76** [mike-lischke/antlr-ng#29]
I'm starting the testing for antlr-ng with the other targets, but that means "official" Antlr4 runtimes. To get this to work, the version string from antlr-ng should match that for "official" antlr4 tool. Right now, it trips up the "official" runtime.

```
ken@DESKTOP-DL44R7B:~/grammars-v4/abb$ bash ../_scripts/test.sh -t Java
Adding abb
Number of grammars before sorting and making unique: 1
Number of grammars after sorting and making unique: 1
Grammars to do are: abb
grammars = abb
targets = Java
order = grammars
filter = all
Tests now abb,Java

abb,Java:
 Build 00:00:04
 Test 00:00:02

========
Parsing tests of abb for Java failed.
Test failed.
ANTLR Tool version 0.4.0 used for code generation does not match the current runtime version 4.13.1
ANTLR Tool version 0.4.0 used for code generation does not match the current runtime version 4.13.1
========
```

I can work around this by updating the templates with an additional step of `sed -i 's/0[.]4[.]0/4.13.1/' *.java`. If I do, the parser works.

**Comment by mike-lischke** [comment]
That's a problem. I cannot start using a high version number, when following semantic versioning. The first official version will be 1.0.0. But something needs to be done to make both compatible, hmm...

**Comment by mike-lischke** [comment]
Maybe introducing a compatibility version (for a while at least) would help? That's just reported to the runtimes, but not used for the releases.

**Comment by mike-lischke** [comment]
I pushed a changed that uses the old tool version (4.13.2) for the code generation. That should do the job for now. The JS/TS runtimes use a different approach, though. I wasn't aware that that there's such a version check in the generated lexer + parser files. I used what I found in the JS runtime <sigh>.

**Comment by kaby76** [comment]
Up to now, the version string was tied to the Antlr tool. That's no longer true, because antlr-ng can write Antlr 4.13.2 or whatever parsers. It's the same problem as having Google or some other app being able to read and write Word "Docx" files, including different versions. The version string has to be considered different from the tool that writes the file. (eiffel builds and runs by the way. The antlr-ng tool seems to work on the grammar, and works with the Antlr 4.13.1 runtime.)

**Comment by mike-lischke** [comment]
I plan to change that in the future. When the target runtime infrastructure is in place, each runtime can declare their compatibility to whatever tool version they want. The tool will not care about that anymore. But that's for the next milestone (and version 2.x of antlr-ng).
